data:extend({
    {
      type = "fluid",
      name = "fluid-coffee",
      icon = "__PreciousPreciousCaffeine__/graphics/fluid_coffee.png",
      icon_size = 64,
      icon_mipmaps = 4,
      base_color = {r=0.22, g=0, b=0},
      flow_color = {r=0.93, g=0.055, b=0},
      subgroup = "coffee-intermediates",
      default_temperature = 20,
      max_temperature = 100,
      order = "z-a",
      always_show_made_in = true,
      enabled = true,
      auto_barrel = true,
    },
    {
      type = "fluid",
      name = "fluid-compressed-air",
      default_temperature = 20,
      max_temperature = 1000,
      icon = "__PreciousPreciousCaffeine__/graphics/fluid_compressed_air.png",
      icon_size = 128,
      icon_mipmaps = 4,
      base_color = {r=0.5, g=0.5, b=0.5},
      flow_color = {r=0.5, g=0.5, b=0.5},
      order = "a[fluid]-b[steam]",
      gas_temperature = 20,
      auto_barrel = false
    },
    {
      type = "fluid",
      name = "fluid-liquid-co2",
      default_temperature = 20,
      max_temperature = 60,
      icon = "__PreciousPreciousCaffeine__/graphics/fluid_co2.png",
      icon_size = 128,
      icon_mipmaps = 4,
      base_color = {r=0.5, g=0.5, b=0.5},
      flow_color = {r=0.5, g=0.5, b=0.5},
      order = "a[fluid]-b[steam]",
      gas_temperature = -50,
      auto_barrel = false
    },
})